version: '3.7'

services:
  bbms:
    container_name: bbms_app
    restart: always
    build: .
    volumes:
      - ./src:/var/www/bbms/src
      - ./test:/var/www/bbms/test
    working_dir: /var/www/bbms
    ports:
      - "9001:9000"
    links:
      - bbms_mysql
    depends_on:
      - bbms_mysql
  
  bbms_mysql:
    image: mysql/mysql-server
    container_name: bbms_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=bbms
      - MYSQL_PASSWORD=bbms
      - MYSQL_DATABASE=bbms
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  db-volume:

networks:
  default:
    name: bbms